# Generated by Django 3.2.8 on 2021-11-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='uodated_at',
            new_name='updated_at',
        ),
    ]
