# Generated by Django 3.2.8 on 2021-11-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_rename_uodated_at_basket_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='updated_at',
            new_name='uodated_at',
        ),
    ]
