# Generated by Django 3.2.8 on 2021-11-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0003_rename_updated_at_basket_uodated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='uodated_at',
        ),
        migrations.AddField(
            model_name='basket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
